 - name: Checkout
   uses: actions/checkout@v1

 - name: Run API Tests
   id: run-newman
   uses: anthonyvscode/newman-action@v1
   with:
    collection: Ak_Tavels.postman_collection.json
    reporters: cli
 - name: Output summary to console
    run: newman run "Ak_Tavels.postman_collection.json"
