
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Newman
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install Newman CLI
      run: npm install -g newman
    - name: Publish Newman CLI
      run: newman publish --gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
